
export const Web3ProviderActions = {
  DISCONNECT_WALLET: 'DISCONNECT_WALLET',
  SET_INJECTED_PROVIDER: 'SET_INJECTED_PROVIDER',
  SET_LOCAL_PROVIDER: 'SET_LOCAL_PROVIDER',
  SET_FALLBACK_PROVIDER: 'SET_FALLBACK_PROVIDER',
}